services:
  db:
    container_name: db_controle_gastos  # Nome do container (opcional)
    image: mysql:latest  # Imagem do MySQL
    ports:
      - "3309:3306"  # Mapeamento de portas
    environment:
      MYSQL_ROOT_PASSWORD: secret  # Senha do MySQL
    volumes:
      - db_data:/var/lib/mysql  # Volume para dados
    networks:
      - project-network  # Rede compartilhada

  app:
    container_name: app_controle_gastos
    build:
      context: .  # Contexto de build
      dockerfile: laravel.Dockerfile  # Dockerfile
    volumes:
      - .:/var/www/html  # Monta diretório
    depends_on:
      - db  # Depende do db
    environment:
      DB_HOST: db  # Banco de dados
      DB_PORT: 3306  # Porta do db
      DB_DATABASE: controle_gastos  # Nome do db
      DB_USERNAME: root  # Usuário do db
      DB_PASSWORD: secret  # Senha do db
    networks:
      - project-network  # Rede compartilhada

  webserver:
    container_name: webserver_controle_gastos
    image: nginx:alpine  # Imagem do Nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Configuração do Nginx
    ports:
      - "8000:80"  # Mapeamento de portas
    depends_on:
      - app  # Depende da app
    networks:
      - project-network  # Rede compartilhada

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    volumes:
      - ./php-custom.ini:/usr/local/etc/php/conf.d/uploads.ini  # Arquivo de configuração personalizado
    depends_on:
      - db
    networks:
      - project-network
networks:
  project-network:  # Rede do projeto
    driver: bridge  # Tipo de rede

volumes:
  db_data:  # Volume para dados do db
